# Generated by Django 4.2.13 on 2025-01-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ejercicio_terminado_ejercicio_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ganada', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias_ganadas', to='myapp.user')),
            ],
        ),
    ]
