# Generated by Django 4.2.13 on 2025-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_usuarioinsignia'),
    ]

    operations = [
        migrations.AddField(
            model_name='insignia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='insignias/'),
        ),
    ]
