# Generated by Django 4.2.13 on 2025-01-11 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_insignia_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insignia',
            name='imagen',
        ),
    ]
