# Generated by Django 4.2.13 on 2025-01-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_insignia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_usuario', to='myapp.user'),
        ),
        migrations.CreateModel(
            name='UsuarioEjercicioInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenida', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ejercicio')),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
