# Generated by Django 4.2.13 on 2025-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_ejercicio_descripcion_alter_ejercicio_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioinsignia',
            name='insignia',
        ),
        migrations.RemoveField(
            model_name='usuarioinsignia',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='foro',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foro',
            name='tema',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='insignia',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logro',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logro',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participacion_foro',
            name='comentario',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='condicion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recompensa',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Foro_respuesta',
        ),
        migrations.DeleteModel(
            name='UsuarioInsignia',
        ),
    ]
