# Generated by Django 4.2.13 on 2025-02-10 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_usuarioinsignia_insignia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_usuario', models.TextField()),
                ('es_correcto', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='myapp.ejercicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='myapp.user')),
            ],
        ),
    ]
