# Generated by Django 4.2.13 on 2025-02-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_ejercicio_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='terminado',
        ),
    ]
