# Generated by Django 4.2.13 on 2025-02-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_ejercicioasignado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicioasignado',
            name='ejercicio_id',
        ),
        migrations.AddField(
            model_name='ejercicioasignado',
            name='ejercicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.ejercicio'),
            preserve_default=False,
        ),
    ]
