# Generated by Django 4.2.13 on 2025-02-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0016_remove_ejercicioasignado_ejercicio_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicioasignado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
