# Generated by Django 4.2.13 on 2025-03-05 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicio',
            old_name='nivel_id',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='intento',
            old_name='ejercicio_id',
            new_name='ejercicio',
        ),
    ]
