# Generated by Django 4.2.13 on 2025-03-05 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_nivel_id_ejercicio_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='myapp.nivel'),
        ),
    ]
