# Generated by Django 4.2.13 on 2025-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_foro_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vidas',
            field=models.IntegerField(default=5),
        ),
    ]
