# Generated by Django 4.2.13 on 2025-03-09 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_intento_usuario_id_intento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='ranking',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_ranking', to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_intentos', to='myapp.user'),
        ),
    ]
