# Generated by Django 4.2.13 on 2025-03-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_ranking_usuario_id_ranking_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidas_restantes', models.IntegerField(default=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vidas_usuario', to='myapp.user')),
            ],
        ),
    ]
