# Generated by Django 4.2.13 on 2025-03-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_vidasusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_insignia',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='usuario_logro',
            name='usuario_id',
        ),
        migrations.RemoveField(
            model_name='usuario_recompensa',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='usuario_insignia',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_insignia', to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario_logro',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_logro', to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario_recompensa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_recompensa', to='myapp.user'),
            preserve_default=False,
        ),
    ]
