# Generated by Django 4.2.13 on 2025-04-12 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participacion_foro',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='participacion_foro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
