# Generated by Django 4.2.13 on 2025-04-12 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_participacion_foro_usuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vidasusuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
