# Generated by Django 4.2.13 on 2025-04-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_vidasusuario_ultima_actualizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='IntentoEjercicio',
        ),
        migrations.DeleteModel(
            name='Ranking',
        ),
    ]
