# Generated by Django 4.2.13 on 2025-04-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_ranking_usuario_delete_intentoejercicio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacion_foro',
            old_name='foro_id',
            new_name='foro',
        ),
    ]
