# Generated by Django 4.2.13 on 2025-04-18 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0033_rename_foro_id_participacion_foro_foro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidasusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vidas_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
